version: '2'
services:
  user_api:
    build: 
      context: .
      dockerfile: ./Dockerfile-user
    container_name: user_api
    command: sh -c "nginx && uwsgi --ini /app/uwsgi.ini --processes 1 --touch-reload /app/user/app/app.py"
    environment:
      PYTHONUNBUFFERED: 0
      MONGODB_HOST: mongo
      MONGODB_USER: connectme
      MONGODB_PASS: mypassword
      MONGODB_DATABASE: users
    volumes:
     - './user:/app/user'
     - './util:/app/util'
    ports:
     - "8110:80"

  auth_api:
    build: 
      context: .
      dockerfile: ./Dockerfile-auth
    container_name: auth_api
    command: sh -c "nginx && uwsgi --ini /app/uwsgi.ini --processes 1 --touch-reload /app/auth/app/app.py"
    environment:
      PYTHONUNBUFFERED: 0
    volumes:
     - './auth:/app/auth'
     - './util:/app/util'
    ports:
     - "8111:80"
  
  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: mongo
    environment:
      MONGODB_USER: 'connectme'
      MONGODB_PASS: 'mypassword'
    ports:
      - "27017:27017"
